[tasks.fmt]
args = ["fmt"]
command = "cargo"
toolchain = "nightly"
workspace = false

[tasks.check]
args = ["check", "--all-features"]
command = "cargo"
workspace = false

[tasks.clippy]
args = ["clippy", "--all-features"]
command = "cargo"
workspace = false

[tasks.test]
args = ["test", "--all-features"]
command = "cargo"
workspace = false

[tasks.checkf]
dependencies = ["fmt", "check"]
workspace = false

[tasks.checkfc]
dependencies = ["fmt", "check", "clippy"]
workspace = false

[tasks.run]
args = ["run", "--", "${@}"]
command = "cargo"
workspace = false
